Update goprofiles.xml
UnsatisfiableError: The following specifications were found to be in conflict:
  - bioconductor-goprofiles 1.44.0*
  - bioconductor-org.mm.eg.db 3.5.0*
Use "conda info <package>" to see the dependencies for each package.

--> go to  r36 and org*db 3.8.2